#!/usr/bin/env python3
# bdf2font.py - Convert a BDF bitmap font into a CastaliaOS 8-row glyph table.
#
# The engine stores each glyph as 8 bytes (8 rows, MSB = leftmost pixel; see
# src/gfx/gfx_font.c). This tool rasterizes a BDF's glyphs for ASCII 32..126
# into that fixed 8-row cell and emits a C array, so a permissively-licensed
# bitmap font (e.g. Spleen 5x8, BSD-2-Clause) can be a selectable system face
# without changing the renderer or any layout metrics.
#
# Only 8-row-tall (or shorter) fonts fit the cell; taller fonts are rejected.
#
# Usage:
#   python3 tools/bdf2font.py in.bdf g_spleen_font8 > src/gfx/gfx_font_spleen.c
import sys

FIRST, LAST = 32, 126


def parse_bdf(path):
    fbb = None
    glyphs = {}
    enc = None
    bbx = None
    bitmap = None
    reading = False
    for line in open(path, 'r', errors='replace'):
        p = line.split()
        if not p:
            continue
        k = p[0]
        if k == 'FONTBOUNDINGBOX':
            fbb = tuple(int(v) for v in p[1:5])       # w h xoff yoff
        elif k == 'ENCODING':
            enc = int(p[1])
        elif k == 'BBX':
            bbx = tuple(int(v) for v in p[1:5])       # w h xoff yoff
        elif k == 'BITMAP':
            reading = True
            bitmap = []
        elif k == 'ENDCHAR':
            reading = False
            if enc is not None and bbx is not None:
                glyphs[enc] = (bbx, bitmap)
            enc = None; bbx = None; bitmap = None
        elif reading:
            bitmap.append(k)
    if fbb is None:
        raise SystemExit('no FONTBOUNDINGBOX')
    return fbb, glyphs


def render_cell(fbb, bbx, bitmap):
    """Rasterize one glyph into 8 bytes (MSB = leftmost), aligned in the cell."""
    fbw, fbh, fbxoff, fbyoff = fbb
    if fbh > 8:
        raise SystemExit('font taller than 8 rows (%d); does not fit the cell' % fbh)
    bw, bh, bxoff, byoff = bbx
    cell = [0] * 8
    cell_top_y = fbyoff + fbh - 1          # y of the cell's top row
    nbytes = (bw + 7) // 8
    total_bits = nbytes * 8
    for i, row in enumerate(bitmap[:bh]):
        val = int(row, 16) if row else 0
        y = byoff + bh - 1 - i             # y of this bitmap row (top row first)
        cell_row = cell_top_y - y
        if cell_row < 0 or cell_row > 7:
            continue
        for gx in range(bw):
            if (val >> (total_bits - 1 - gx)) & 1:
                col = gx + bxoff - fbxoff
                if 0 <= col <= 7:
                    cell[cell_row] |= (0x80 >> col)
    return cell


def main(argv):
    if len(argv) < 3:
        sys.stderr.write('usage: bdf2font.py in.bdf array_name > out.c\n')
        return 1
    path, name = argv[1], argv[2]
    fbb, glyphs = parse_bdf(path)
    out = sys.stdout
    out.write('/*\n')
    out.write(' * %s - generated by tools/bdf2font.py; DO NOT EDIT BY HAND.\n' % name)
    out.write(' *\n')
    out.write(' * ASCII %d..%d rendered into the 8-row glyph cell (see gfx_font.c).\n'
              % (FIRST, LAST))
    out.write(' * Source font: %s (FONTBOUNDINGBOX %d %d %d %d).\n'
              % (path.split('/')[-1], fbb[0], fbb[1], fbb[2], fbb[3]))
    out.write(' * Regenerate with: make gen-font\n')
    out.write(' */\n\n')
    n = LAST - FIRST + 1
    out.write('const unsigned char %s[%d][8] = {\n' % (name, n))
    for code in range(FIRST, LAST + 1):
        if code in glyphs:
            bbx, bmp = glyphs[code]
            cell = render_cell(fbb, bbx, bmp)
        else:
            cell = [0] * 8
        bytes_str = ','.join('0x%02X' % b for b in cell)
        ch = chr(code) if code != 92 else '\\\\'
        out.write('    { %s },  /* %d  %s */\n' % (bytes_str, code, ch))
    out.write('};\n')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
