#!/usr/bin/env python3
# gen_presskit_logo.py - Bake the press kit's crest icons and favicon from the
# ONE source the product itself uses.
#
# The press kit shipped a crest that was not the product's mark. Its icons were
# generated by tools/gen_logo.c, which bakes sh_logo.c's PROCEDURAL drawing --
# correct when that drawing was the mark, and stale from the moment the shell
# started preferring the icon pack's logo-*.bmp. So the desktop showed one
# castle and the press kit showed another, and nothing said so, because both
# were being generated correctly from different places.
#
# Everything here comes from presskit/castalia-98-logo.png, which is also what
# assets/icons/*/logo-*.bmp are baked from (see assets/icons/README.md). One
# source, so the two cannot drift apart again.
#
# Pure Python standard library (zlib only) -- no Pillow, same as png2bmp.py,
# because the rest of this repo's asset pipeline runs on a bare python3 and
# adding a dependency for one script is not worth it.
#
# Usage:  python3 tools/gen_presskit_logo.py        (from the repo root)

import os
import struct
import sys
import zlib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from png2bmp import load_png, resize_area          # noqa: E402

SRC = 'presskit/castalia-98-logo.png'
OUT = 'presskit/logo'
ICON_SIZES = (256, 64)          # the two crest PNGs the press kit offers
ICO_SIZES = (16, 32, 48, 64)    # what favicon.ico carries


def pad_square(w, h, px):
    """Letterbox to a square with transparent margins.

    The source is 256x269 -- taller than it is wide -- and stretching it to a
    square would make the castle squat. png2bmp's --pad does the same thing for
    the icon packs, so the crest here and the crest on the Start button are the
    same shape.
    """
    if w == h:
        return w, h, px
    side = max(w, h)
    ox, oy = (side - w) // 2, (side - h) // 2
    blank = (0, 0, 0, 0)
    out = [[blank] * side for _ in range(side)]
    for y in range(h):
        for x in range(w):
            out[oy + y][ox + x] = px[y][x]
    return side, side, out


def write_png(path, w, h, px):
    raw = bytearray()
    for y in range(h):
        raw.append(0)                       # filter: none
        for x in range(w):
            r, g, b, a = px[y][x]
            raw += bytes((r, g, b, a))

    def chunk(tag, data):
        body = tag + data
        return (struct.pack('>I', len(data)) + body +
                struct.pack('>I', zlib.crc32(body) & 0xFFFFFFFF))

    png = b'\x89PNG\r\n\x1a\n'
    png += chunk(b'IHDR', struct.pack('>IIBBBBB', w, h, 8, 6, 0, 0, 0))
    png += chunk(b'IDAT', zlib.compress(bytes(raw), 9))
    png += chunk(b'IEND', b'')
    with open(path, 'wb') as f:
        f.write(png)
    print('  %s (%dx%d)' % (path, w, h))


def ico_dib(w, h, px):
    """One ICO entry as a 32-bit BMP DIB.

    Not an embedded PNG. PNG-in-ICO needs Vista or newer to decode, and the
    whole point of a favicon is that everything reads it -- including the
    browsers somebody looking at a retro-DOS press kit is plausibly using.
    The DIB is bottom-up and carries its own AND mask, which is required by
    the format even when the alpha channel already answers the question.
    """
    hdr = struct.pack('<IiiHHIIiiII', 40, w, h * 2, 1, 32, 0, w * h * 4,
                      0, 0, 0, 0)
    body = bytearray()
    for y in range(h - 1, -1, -1):
        for x in range(w):
            r, g, b, a = px[y][x]
            body += bytes((b, g, r, a))     # BGRA
    mask_row = ((w + 31) // 32) * 4         # padded to 4 bytes
    body += bytes(mask_row * h)             # all-opaque AND mask
    return hdr + bytes(body)


def write_ico(path, images):
    n = len(images)
    out = struct.pack('<HHH', 0, 1, n)
    offset = 6 + 16 * n
    blobs = []
    for (w, h, px) in images:
        dib = ico_dib(w, h, px)
        blobs.append(dib)
        out += struct.pack('<BBBBHHII', w if w < 256 else 0,
                           h if h < 256 else 0, 0, 0, 1, 32,
                           len(dib), offset)
        offset += len(dib)
    with open(path, 'wb') as f:
        f.write(out + b''.join(blobs))
    print('  %s (%s)' % (path, ', '.join(str(i[0]) for i in images)))


def main():
    if not os.path.exists(SRC):
        print('gen_presskit_logo: %s is missing' % SRC, file=sys.stderr)
        return 1
    w, h, px = load_png(SRC)
    w, h, px = pad_square(w, h, px)
    print('gen_presskit_logo: from %s (%dx%d square)' % (SRC, w, h))

    for size in ICON_SIZES:
        nw, nh, out = resize_area(w, h, px, size, size)
        write_png(os.path.join(OUT, 'castaliaos-icon-%d.png' % size),
                  nw, nh, out)

    images = []
    for size in ICO_SIZES:
        nw, nh, out = resize_area(w, h, px, size, size)
        images.append((nw, nh, out))
    write_ico(os.path.join(OUT, 'favicon.ico'), images)
    return 0


if __name__ == '__main__':
    sys.exit(main())
